## NumPy 배열 특징

In [2]:
import numpy as np

np.random.seed(0)  # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size=6)  # 1차원 배열

x2 = np.random.randint(10, size=(3, 4))  # 2차원 배열

x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 배열

In [21]:
x1 = np.random.randint(10, size=6) # 1차원 배열

x2 = np.random.randint(10, size=(3, 4)) # 2차원 배열

x3 = np.random.randint(10, size=(3, 4, 5)) # 3차원 배열

print("x3 ndim: ", x3.ndim)

print("x3 shape:", x3.shape)

print("x3 size: ", x3.size)

#### 배열 데이터 타입 확인

print("dtype:", x3.dtype)

## 배열 인덱싱

x1[0]

x1[4]

#### 맨 끝 인자 확인

x1[-1]

x1[-2]

#### 다차원 배열은 콤마 , 로 구분하여 접근

x2[0, 0]

x2[2, 0]

x2[2, -1]

#### 배열의 값은 인덱싱을 통해 바꿀 수 있다.

x2[0, 0] = 12

x2

#### Numpy 배열은 파이썬과 달리 고정 타입을 가지기 때문에 기본 타입이랑 다른 값이 들어오면 기본 타입으로 cascating한다.

x1[0] = 3.14159  # 이 값의 소수점 이하는 잘릴 것이다!

x1

## Array Slicing: Accessing Subarrays

### One-dimensional subarrays

x = np.arange(10)
x

#### 첫 다섯 개의 요소
x[:5]  

#### 인덱스 5 다음의 요소들
x[5:]  

#### 중간 하위 배열
x[4:7]  

#### 하나 걸러 하나씩의 요소들로 구성된 배열
x[::2]  

#### 인덱스 1로부터 시작하여 하나 걸러 하나씩 요소들로 구성된 배열
x[1::2] 

#### 모든 요소들을 거꾸로 나열
x[::-1] 

#### 인덱스 5부터 하나 걸러 하나씩 요소들을 거꾸로 나열
x[5::-2]  

### Multi-dimensional subarrays

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### 두 개의 행, 세 개의 열
x2[:2, :3]  

#### 모든 행, 한 열 걸러 하나씩
x2[:3, ::2] 

x2[::-1, ::-1]

#### Accessing array rows and columns

#### x2의 첫 번째 열

print(x2[:, 0])  

#### x2의 첫 번째 행
print(x2[0, :])  

#### x2[0, :] 와 동일
print(x2[0])  

### Subarrays as no-copy views

print(x2)

#### $2 \times 2$ subarray

x2_sub = x2[:2, :2]

print(x2_sub)

x2_sub[0, 0] = 99

print(x2_sub)

print(x2)

### Creating copies of arrays

In [18]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  2]
 [ 8  2]]


If we now modify this subarray, the original array is not touched:

In [19]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  2]
 [ 8  2]]


In [20]:
print(x2)

[[99  2  2  5]
 [ 8  2  6  0]
 [ 4  1  2  3]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [38]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [39]:
x = np.array([1, 2, 3])

# reshape 을 이용한 행 벡터
x.reshape((1, 3))

array([[1, 2, 3]])

In [40]:
# newaxis를 이용한 행 벡터
x[np.newaxis, :]

array([[1, 2, 3]])

In [41]:
# reshape을 이용한 열 벡터
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [42]:
# newaxis를 이용한 열 벡터
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

### Concatenation of arrays

In [43]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

#### 2개 이상 배열 Concat

z = [99, 99, 99]

print(np.concatenate([x, y, z]))

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

#### 첫 번째 축을 따라 연결
np.concatenate([grid, grid])

#### 두 번째 축을 따라 연결(0부터 시작되는 인덱스 방식) 
np.concatenate([grid, grid], axis=1)

x = np.array([1, 2, 3])

grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

#### 배열을 수직적으로 쌓음 
np.vstack([x, grid])

#### 배열을 수평적으로 쌓음
y = np.array([[99],
              [99]])
              
np.hstack([grid, y])