# 배열 연산 : Broadcasting

## 브로드 캐스팅 

#### 동일한 크기의 배열은 element-wise 연산을 한다.

In [6]:
import numpy as np

In [7]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

#### 브로드캐스팅을 사용하면, 서로 다른 크기의 배열을 계산할 수 있다.
배열에 스칼라(0차원 배열)을 더할 수 있다.

In [8]:
a + 5

array([5, 6, 7])

### 고차원 배열 브로드캐스팅 예시


In [9]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [12]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

공통 크기를 맞추기 위해 a, b 모두 브로드캐스팅을 하였고, 공통 크기인 (3, 3) 크기의 배열을 생성하였다.

![Broadcasting Visual](figures/02.05-broadcasting.png)

## 브로드캐스팅 규칙

- 규칙 1. 두 배열의 차원수가 다르면 더 작은 수의 차원을 가지 ㄴ배열 크기의 앞쪽을 1로 채운다.
- 규칙 2. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른형상과 일치하도록 늘어난다.
- 규칙 3. 임의의 차원에서 크기가 일치하지 않고, 1도 아니라면 오류가 발생.

### 예시 1


In [13]:
M = np.ones((2, 3))
a = np.arange(3)

Let's consider an operation on these two arrays. The shape of the arrays are

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

규칙 1에 따라 배열 a가 더 작은 차원을 가지고 있으므녀 왼쪽을 1로 채운다.

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

규칙 2에 의해, 첫번째 차원이 일치하지 않으므로 이 차우너이 일치하도록 늘린다.

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

In [14]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### 브로드캐스팅 예제 2

In [15]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

Again, we'll start by writing out the shape of the arrays:

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 says we must pad the shape of ``b`` with ones:

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

Because the result matches, these shapes are compatible. We can see this here:

In [16]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 브로드캐스팅 예제 3

In [17]:
M = np.ones((3, 2))
a = np.arange(3)

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``


- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``


- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

In [18]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [19]:
a[:, np.newaxis].shape

(3, 1)

In [20]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])